### ISSUE TITLE
Request for Info

### ISSUE THREAD

**Issue by woody4165** [JXGA/ESP8266-NTP-Clock#1]
Hi and thanks for sharing your project!

I have printed a case for a 4 modules of MAX7219, but I see it upside down

How can I change text orientation?

I tried with this code

```
  matrix.fillScreen(0);
  matrix.setIntensity(0); // Use a value between 0 and 15 for brightness
  matrix.setRotation(0, 1);    // The first display is position upside down
  matrix.setRotation(1, 1);    // The first display is position upside down
  matrix.setRotation(2, 1);    // The first display is position upside down
  matrix.setRotation(3, 1);    // The first display is position upside down
  display_message("Ready");
```

I changed value 1 to 0,  then 2 and 3 and 180, but none of them works.

Is this the correct part of code to change?
And what value should I use?

Thanks

**Comment by JXGA** [comment]
Hello! 

It has been a **long** time since I've looked at this, but I'll try my best to help... 

In the `Max72xxPanel.h` file it includes this: 

```
	/*
	 * Define if and how the displays are rotated. The first display
	 * (0) is the one closest to the Arduino. rotation can be:
	 *   0: no rotation
	 *   1: 90 degrees clockwise
	 *   2: 180 degrees
	 *   3: 90 degrees counter clockwise
	 */
	void setRotation(byte display, byte rotation);
```

So `matrix.setRotation(3, 1);` would be the fourth display in the sequence (as it starts at zero) and the `1` indicates a rotation through 90 degrees. 

Can you confirm when you changed the second byte to `0`, `2` or `3`, did it do _anything_ to the displays?

I vaguely remember turning my displays upside down to fit them in the case... it's been a while though and don't know if this is a real 'fix'.

Let me know how above goes and we can look further.

**Comment by woody4165** [comment]
Hi @JXGA  and thanks for replying

When I use 3 as value, I get the rotation I need, but the text messages are written for each single module and scroll only in that module, so the text "Ready" are written for module 1,2,3 and 4 instead of scrolling as a single text.
The clock has the values non in the proper order, so it seems that the rotation value is bot the only things to adjust for my needs.

Using 1 and 2 as rotation value, I get vertical string for each single module, and same as before for the clock, the single numbers are not in the proper order.

So probably, I have to test more to understand how to let it work, or just reprint my case mirrored, that is probably easier....

**Comment by JXGA** [comment]
Hey @woody4165, 

Did you resolve this? Any clues for anyone reading this in future?

Thanks

**Comment by woody4165** [comment]
Hi @JXGA 

Nope, I'm sorry, I haven't found a solution. I'm a newbie on Max7219 and I'm pretty sure there is something else to modify to let it works....

**Comment by Cooper81** [comment]
matrix.setPosition(0, 3, 0); // (Display-Nr ab Einspeisung, X, Y)
  matrix.setPosition(1, 2, 0);
  matrix.setPosition(2, 1, 0);
  matrix.setPosition(3, 0, 0);
  
  matrix.fillScreen(0);
  
  matrix.setIntensity(0); // Use a value between 0 and 15 for brightness
  matrix.setRotation(0, 3);    // The first display is position upside down
  matrix.setRotation(1, 3);    // The first display is position upside down
  matrix.setRotation(2, 3);    // The first display is position upside down
  matrix.setRotation(3, 3);    // The first display is position upside down
  display_message("Ready");

`this will resolve ur problem`

**Comment by JXGA** [comment]
@woody4165, does this resolve the issue?

Thanks

**Comment by woody4165** [comment]
Thanks, it seems to solve it!

**Comment by JXGA** [comment]
Excellent! 

Thanks @Cooper81 & @woody4165
