### ISSUE TITLE
weird time/symbols

### ISSUE THREAD

**Issue by damver** [JXGA/ESP8266-NTP-Clock#2]
can u explain this and how to fix it?
 im running it on a wemos d1 mini

![IMG_7029](https://user-images.githubusercontent.com/26824168/121396086-4e6a7400-c953-11eb-873b-e19f60c082bd.jpg)

**Comment by JXGA** [comment]
Hello. 

Any changes with this issue or still occurring? 

Have you definitely set the number of displays correctly, and what is the expected value on the display? (Time, MQTT message?). 

It might be worth wiping most of the code out and trying to display a simple message to see if everything is loading correctly.

**Comment by JXGA** [comment]
Closing as stale
