### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by Cooper81** [JXGA/ESP8266-NTP-Clock#3]
Hi!
thx for this great project.
is there a way to change basic settings over mqtt?
for example: brightness, scrollspeed, display on/off, ....

thanks

**Comment by JXGA** [comment]
Hi @Cooper81 

There isn't at the moment - I'd love a PR if you were interested in giving it a shot! 

Thanks

**Comment by Cooper81** [comment]
What does it mean "PR"?

**Comment by JXGA** [comment]
A pull request - if you are able to develop the code to allow MQTT to control the device, you can create a pull request to update this project repository.

**Comment by Cooper81** [comment]
Oh, Sorry.
Of cause 😁
Im not a programmer.... So i cant, sorry.
But im gonna ask my neighbour. Maybe He can

Greetings

**Comment by JXGA** [comment]
Hey @Cooper81 

The latest commit (69e9aba) now has 'brightness' (nodeNTP_1/bright, thanks to @Matthew-Kent !) and 'shutdown' (nodeNTP_1/shutdown) to switch off the display via MQTT. 

Brightness uses values between 0-15 and the default brightness can be set in the code by 'defaultBrightness'. 

Shutdown will accept MQTT string (true/True/TRUE/1) to switch off the display or any other value to switch it on. 

We don't currently control the scroll speed via this code but if you'd like to add it, feel free to open a PR !

Will close this now :-)

**Comment by Cooper81** [comment]
Many thx

**Comment by JXGA** [comment]
@Matthew-Kent made an improvement to the shutdown MQTT - now you can just use brightness "0" to shut off the display which is a lot more elegant!

Latest version therefore won't allow MQTT shutdown command.
