### ISSUE TITLE
Stopped working...

### ISSUE THREAD

**Issue by Matthew-Kent** [JXGA/ESP8266-NTP-Clock#4]
I've been using a modified version of your code to run a couple of clocks around my house.  Wanted to be able to adjust the brightness via mqtt so I recompiled and uploaded using latest libraries and Arduino IDE.  It looks like there's been a change somewhere that's affecting the string building of `myTime = myTime + "0" + actualHour;` - I get garbage out.  To resolve I had to cast actualHour (actually all the instances returned from NTPtimeESP used to build the myTime string) to a string: `myTime = myTime + "0" + String(actualHour);`  Then it all seems okay.  Hope this helps, I'm pretty new all this.

**Comment by JXGA** [comment]
Hi @Matthew-Kent 

Thanks for the report! 

I haven't looked at this in a long time so haven't noticed any library changes. 

Do you have a working file you could share by opening a pull request, then we can update it for everyone who comes to view in future? 

Thanks

**Comment by Matthew-Kent** [comment]
I'm not quite sure what I'm doing, but I think I've stared a pull request....

**Comment by JXGA** [comment]
Appreciate the PR! 

Very impressed with the improved NTP code. Do you know if there's a way to send an MQTT message when NTP updates (or fails to update?), or customise the poll time?

I've added a couple of bits and re-commited without version numbers in the file name. 

- Add 'shutdown' MQTT to switch off MAX displays (nodeNTP_1/shutdown)
- Add defaultBrightness (set to 0 but easily changed)
- Add debugMode (reduces amount of console text with time changes)

Thank you 😀
